### ISSUE TITLE
Devnet Checklist

### ISSUE THREAD

**Issue by cloudhead** [oscoin/oscoin#395]
## Core protocol

* [ ] Block validation
	* [x] Basic block validation
	* [ ] Two-phase validation
	* [ ] Testing
* [ ] Chain scoring
	* [x] Fork selection
	* [ ] Real scoring function
* [x] Miner
* [x] Network simulator
* [x] Block storage
	* [x] In-memory
	* [x] SQLite
* Light-client friendly design
	* [ ] Specification
* Smart contract integration
	* [ ] Plan
* [ ] Gossip
	* [x] EBTs
	* [x] HyParView
	* [x] Handshake protocol
	* [ ] LAN discovery
	* [ ] WAN discovery
	* [ ] Reconciliation tests
* [ ] Account address format
* [ ] Dynamic membership tests and simulations
* [x] API
	* [x] Blocks
	* [x] Transactions
* [ ] Transactions
	* [x] Mempool
	* [x] Validation
	* [ ] CLI

## Operations

* [ ] Telemetry
	* [x] Instrumentation
	* [x] Logging
	* [ ] Dashboards
* [ ] Automated deployment
