### ISSUE TITLE
Testnet-1 WIP Checklist

### ISSUE THREAD

**Issue by cloudhead** [oscoin/oscoin#396]
## Core protocol

* [ ] Accounts
  * [ ] Balances
  * [ ] Transfer transactions
  * [ ] Address format

* [ ] Light-client-friendly design

* [ ] Project registry MVP
  * [ ] `Register` transaction
  * [ ] `Unregister` transaction
  * *stretch*: [ ] `Checkpoint` transaction

* [ ] Smart contracts
  * [ ] Interfaces and integration
  * [ ] Basic contract MVPs (no voting)
    * [ ] `sendTransfer`
    * [ ] `receiveTransfer`
    * [ ] `receiveReward`
    * [ ] `updateContract`

* [ ] Block reward
  * [ ] To miners
  * [ ] To projects (mock-*osrank*)

## Operations

* [ ] Public CI/CD
* [ ] Linux packaging
