### ISSUE TITLE
Git remote-helper

### ISSUE THREAD

**Issue by cloudhead** [oscoin/oscoin#5]
A [git-remote-helper](https://git-scm.com/docs/git-remote-helpers) that can push to and pull from a node. This depends entirely on the interfaces exposed on the node.

```
$ git remote add oscoin oss://zdvgqEMYmNeH5fKciougvQcfzMcNjF3Z1tPouJ8C7pc3pe63k
$ git push -u oscoin master
```

## TODO

- [ ] Find way to read storage backend URLs from config file (i.e. .git/config, or something else)
- [ ] Read static node IP addresses from config
- [ ] Push and update Git metadata on chain
  - [ ] Create branches on-chain
  - [ ] Update branch HEAD on chain
  - [ ] Delete branches on chain
  - [ ] Read branch HEAD from chain
- [ ] Pull and validate consistency with Git metadata on chain

A good example of this can be found here: https://github.com/cjb/GitTorrent/blob/master/git-remote-gittorrent

Working branch/PR: https://github.com/oscoin/oscoin/pull/204
