### ISSUE TITLE
Run node with OscoinTx

### ISSUE THREAD

**Issue by geigerzaehler** [oscoin/oscoin#568]
## Problem

At the moment the node runs with `Oscoin.Data.Tx.Tx` as the transaction type. For the devnet we need to run it with `Oscoin.Data.OscoinTx.Tx` as the transaction type.

## Solution/implementation plan

We need to create issues and spec out the following

- [x] Implement Sqlite persistence for OscoinTx (#590)
- [x] Provide a `Serialise` instance for OscoinTx (#590)
- [x] CLI can generate valid genesis block for OscionTx (#589)
- [x] Replace `Evaluator` that can only evaluate txs with block data evaluator. The oscoin ledger exposes `applyTxMessages` which applies all txs in a block in bulk and needs to know about the beneficiary. (#591)

There is probably something missing here.

**Comment by cloudhead** [comment]
Closed by #607
